[variables]
    NODE_ENV = "production"

[phases.build]
    cmd = "npm ci && npm run build"

[phases.start]
    cmd = "npx serve -c serve.json -l 3000"
    
[start]
    cmd = "npx serve -c serve.json -l 3000"